use firstdb;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `FIRST_PROCEDURE`()
BEGIN
DECLARE VAR_EMP_ID INT(5);
SET VAR_EMP_ID:= 1301;
SELECT EMPLOYEE_ID,FNAME FROM EMPLOYEE_REC WHERE EMPLOYEE_ID =  VAR_EMP_ID;
END$$
DELIMITER ;
